version: '3'
services:
  feedback-service:
    build: ./Feedback
    volumes:
      - './Feedback/db:/home/node/app/db'
      - './Feedback/src:/home/node/app/src'
    expose:
      - "5009"
  food-service:
    build: ./FoodRest
    expose:
      - "7000"